### ISSUE TITLE
Order History API and Complains API

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#1]
The Order History API is returning null when I hit it.
The body of complains API is returning 

{"href":"stage.dmenu.co:3005/api/v1/users/58e16ed1f9db495e5e797688/complains","data":[{"complains":[{"isActive":true,"_id":"58e16ed9f9db495e5e797689"}]}]}

**Comment by afirdousi** [comment]
Each issue should talk about 1 and only 1 issue. Please do not open one issue discussing more than one api.

I am closing this one. Open 2 separate issues for each problem.
