### ISSUE TITLE
Remove authentication from forgot password Api

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#10]
**'api/v1/users/password/forgot'** 

This Api is returning 403 forbidden error, 
![screen shot 2017-04-18 at 11 42 33 am](https://cloud.githubusercontent.com/assets/7201838/25118351/5eed9ce4-242f-11e7-94e8-033982a0fafd.png)

when in app.js this line is commented **app.use(kcAuth());** Api starts working fine.

**Comment by afirdousi** [comment]
Didn't we fix this already? Let me check again. Sorry for this.

**Comment by afirdousi** [comment]
Fixed. Please test.
