### ISSUE TITLE
Add 'x-access-token' header in Access-Control-Allow-Headers in app.js

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#11]
![screen shot 2017-04-18 at 12 15 37 pm](https://cloud.githubusercontent.com/assets/7201838/25119524/f3b73b92-2433-11e7-8756-2ae6281af4f7.png)

when there is no **"x-access-token"** header in Access-Control-Allow-Headers, all patch requests stops working with error **"Request header field x-access-token is not allowed by Access-Control-Allow-Headers in preflight response."** it works from **postman or any rest client tool** but not from browser

As our app is an hybrid app it runs on web browser of device so all the requests are originated from browser.
 As soon we add this header in app.js
**
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,PATCH');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization','x-access-token');
**
patch api's works fine in browser

**Comment by afirdousi** [comment]
okay.

do you want me to add all these suggested headers explicitly as you have mentioned?
