### ISSUE TITLE
Order history Api returns empty array

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#13]
**/api/v1/orders/user/58f493a9fae8c00ce2161932**

![screen shot 2017-04-18 at 1 03 19 pm](https://cloud.githubusercontent.com/assets/7201838/25120435/7be41dfc-2437-11e7-9955-6bb937b364e6.png)

After struggling for hours we came to know that the reason why this Api was returning objects in array for you but not for us was that the order you created contains key **"userID"** field, but none of the patch request we are consuming takes an argument of "userID" in **"Orders"** document.

The code for finding data in node server is to match userID with the ID we are sending you in the GET api url, but all of the orders that we have created doesn't contain ''userID' field so it won't match to any records in "Orders" document therefore returns empty array.

**Comment by afirdousi** [comment]
You should not have invested hours into this in first place.

If you are familiar with REST, the URL says it all
`/api/v1/` >> in version 1 of apis
`orders/` >> look in all orders 
`user/` >> only for user
`:userID` >> with user ID this

**Comment by afirdousi** [comment]
For exact structure how a order should look like please refer to the 2 dummy orders in current dump

**Comment by afirdousi** [comment]
You are right. The `/pregen/order` should be asking you for `userID` initialing while creating the shell/skeleton order.

**Comment by afirdousi** [comment]
let me change 
`/pregen/order`
to
`/pregen/order/user/:userID`

**Comment by afirdousi** [comment]
This should be fixed with this [new commit](https://github.com/kc-laundry/kc-node/commit/7b818f601aa69563b51626b9925513353143f2d3). Please test.

**Comment by asad-khan92** [comment]
Actually the time wasn't spend on looking for the method, the time was spent on why it is working for you and not for us because the code is same for both of us...
