### ISSUE TITLE
KC-Auth

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#3]
Authentication is applied on sign up and signin also.

**Comment by afirdousi** [comment]
I don't think so. The order of the node server code is

```
app.use('/api/v1/auth', require('./auth'));

app.use(kcAuth());

app.use('/api/v1/orders', orders);
app.use('/api/v1/users', users);
app.use('/api/v1/laundryItems', laundryItems);
app.use('/api/v1/appVersion', appVersion);
```

where the auth middleware `kcAuth()` is pulled in after the `/auth` routes. So only the routes after `kcAuth()` should be protected. 

Can you provide more details please?

**Comment by afirdousi** [comment]
I am able to run `http://localhost:3000/api/v1/auth/local` without any auth tokens.

**Comment by afirdousi** [comment]
Can you provide more details ?

**Comment by afirdousi** [comment]
You are right. The basic signup API ` POST /api/v1/users/ ` also requires token. Fixing it now...

**Comment by afirdousi** [comment]
The sign up API has changed a little and does not require auth token any more. Please check [this new commit for the new API changes](https://github.com/kc-laundry/kc-node/commit/ce7ea7d19502522fdde3e73a4f55170afe2d59d1)

**Comment by afirdousi** [comment]
Sign in API has no issues and does not require token so there is no fix for that.
