### ISSUE TITLE
Headers not allowed.

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#4]
Please allow x-access-token header in the server code.

**Comment by afirdousi** [comment]
I don't think it is not allowed. Again there is no detail about the issue as to what is happening ?

**Comment by afirdousi** [comment]
Please specify the exact requirements here regarding this issue. Thanks.

**Comment by afirdousi** [comment]
Here are some more details as to how server authentication middleware works and where it looks for auth tokens:

```
...
var token = req.body.token || req.query.token || req.headers['x-access-token'];
...
```

It first checks to see if you are sending `token` directly in `body`... if not then are you sending `token` in `query` if not only then it checks for `x-access-token` in the request header.

Do you want me to change this and make the middleware look for `x-access-token` in header first and then at any other place?
