### ISSUE TITLE
Order history API returning null

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#5]
The Order History API is returning null when I hit it.

**Comment by afirdousi** [comment]
When opening issues, please provide more details. Exact URL of API, exact error + any snapshots.

**Comment by afirdousi** [comment]
I don't see any errors for `http://localhost:3000/api/v1/orders/user/58bfb4c8685648cd039296d2` and it is returning the data perfectly fine.

Are you talking about this API ?

**Comment by afirdousi** [comment]
Check if this [new commit](https://github.com/kc-laundry/kc-node/commit/d963d9a74beb502c838995ab43b050d0117a00a9) fixes your issue? The `/orders/user/:userID/` was returning only 1 order for this user. Now it is returning all orders.

**Comment by afirdousi** [comment]
Check the latest dump of mongo `kc-laundry-2017-4-16-2.zip` . I have added 2 sample orders for user ID `58bfb4c8685648cd039296d2`
