### ISSUE TITLE
Complain API is not returning data

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#6]
The body of complains API is returning

{"href":"stage.dmenu.co:3005/api/v1/users/58e16ed1f9db495e5e797688/complains","data":[{"complains":[{"isActive":true,"_id":"58e16ed9f9db495e5e797689"}]}]}

**Comment by afirdousi** [comment]
You looks perfectly fine. You have to save some complain to get that complain.

I just tested and it looks good.

Running `http://localhost:3000/api/v1/users/58bfb4c8685648cd039296d2/complains`

Returned the following:
```
{
  "href": "localhost:3000/api/v1/users/58bfb4c8685648cd039296d2/complains",
  "data": [
    {
      "complains": [
        {
          "_id": "58d941169cfbba22aa5b5e04",
          "complain": "This is a complain ... did you get it ?",
          "isActive": true
        },
        {
          "_id": "58d9412c9cfbba22aa5b5e05",
          "complain": "Second complain... please fix this...",
          "isActive": true
        }
      ]
    }
  ]
}
```

**Comment by afirdousi** [comment]
In your case the `complain` field is missing because there must be no text saved in complain.

**Comment by afirdousi** [comment]
I also tested the `PATCH` call and it is running fine. Read the commit messages for `complain/suggestion` apis i commited 21 days aga >> [complain/suggestion commit](https://github.com/kc-laundry/kc-node/commit/976c66916eb1b7e59dd689751fdfc5cf936c7cd0)
