### ISSUE TITLE
Notifications API is not modifying the data

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#7]
Notifications API is not modifying the data and returning nModified=0

**Comment by afirdousi** [comment]
Again there is no detail specified about the issue.

If you are talking about this call `PUT http://localhost:3000/api/v1/users/58bfb4c8685648cd039296d2/notificationSettings` 

This is working perfectly fine on my end and is returning 
```
{
  "href": "localhost:3000/api/v1/users/58bfb4c8685648cd039296d2/notificationSettings",
  "data": {
    "n": 1,
    "nModified": 1,
    "ok": 1
  }
}
```
