### ISSUE TITLE
SignUp API, no token

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#8]
Upon hitting SignUp API it is not returning the x-access-token. The response from the server is:
"{"href":"localhost:3005/api/v1/users/","data":{"__v":0,"userName":"john","password":"950fe7f5","facebookName":"","dob":"1990-01-01","customerLevel":"B","customerType":"I","isActive":true,"_id":"58ece645c9af9d20f5854f77","complains":[],"contact":{"phone1":"123456789","phone2":"","email1":"john@doe.com","email2":"","address":[]}}}"

**Comment by afirdousi** [comment]
The sign-up API can but should not return the token. That violates separation of concerns.

After the user successfully signs up, please make call to the same `/api/v1/auth/local` API sending user's newly created username and password to get the token.

No new API needed.
