### ISSUE TITLE
Forgot Password API 

### ISSUE THREAD

**Issue by asad-khan92** [kc-laundry/kc-node#9]
In forgot password API, 
1) The URL is incorrect.
2) The field is USER ID, however it should be user email.

**Comment by afirdousi** [comment]
Again very vague details ... Which API exactly ?

Looks like I kept the wrong URL in my commit message:
 `GET /api/v1/users/:userID/forgotPassword `

the correct URL is  `GET  /api/v1/users/:userID/password/forgot`

I am sorry this is my mistake

**Comment by afirdousi** [comment]
I thought we are going to cache `userID` on the phone hence this works with `userID` ... you want me to change it to `email`?

**Comment by afirdousi** [comment]
This feature has been added. Check this new API [in this commit](https://github.com/kc-laundry/kc-node/commit/d3ab5c2413cc8447d73ba3f3a14abdd82fa7ad95)
